#!/bin/bash
FILE="apps/android/app/src/main/java/ai/openclaw/app/ui/SettingsSheet.kt"

# 批量替换设置界面的字符串
sed -i 's/Text("Name", style = mobileCaption1, color = mobileTextSecondary)/Text(stringResource(R.string.name), style = mobileCaption1, color = mobileTextSecondary)/g' "$FILE"
sed -i 's/Text("Default Assistant", style = mobileHeadline)/Text(stringResource(R.string.default_assistant), style = mobileHeadline)/g' "$FILE"
sed -i 's/Text("Microphone", style = mobileHeadline)/Text(stringResource(R.string.microphone), style = mobileHeadline)/g' "$FILE"
sed -i 's/Text("Photos and video clips (foreground only).", style = mobileCallout)/Text(stringResource(R.string.photos_video), style = mobileCallout)/g' "$FILE"
sed -i 's/Text("Camera", style = mobileHeadline)/Text(stringResource(R.string.camera), style = mobileHeadline)/g' "$FILE"
sed -i 's/Text("System Notifications", style = mobileHeadline)/Text(stringResource(R.string.system_notifications), style = mobileHeadline)/g' "$FILE"
sed -i 's/Text("Alerts and foreground service.", style = mobileCallout)/Text(stringResource(R.string.alerts_foreground), style = mobileCallout)/g' "$FILE"
sed -i 's/Text("Notification Listener Access", style = mobileHeadline)/Text(stringResource(R.string.notification_listener), style = mobileHeadline)/g' "$FILE"
sed -i 's/Text("SMS", style = mobileHeadline)/Text(stringResource(R.string.sms), style = mobileHeadline)/g' "$FILE"
sed -i 's/Text("Send and search SMS from this device.", style = mobileCallout)/Text(stringResource(R.string.send_search_sms), style = mobileCallout)/g' "$FILE"
sed -i 's/Text("Forward Notification Events", style = mobileHeadline)/Text(stringResource(R.string.forward_notification), style = mobileHeadline)/g' "$FILE"
sed -i 's/Text("Package Filter: Allowlist", style = mobileHeadline)/Text(stringResource(R.string.package_filter_allow), style = mobileHeadline)/g' "$FILE"
sed -i 's/Text("Only listed package IDs are forwarded.", style = mobileCallout)/Text(stringResource(R.string.only_listed_forwarded), style = mobileCallout)/g' "$FILE"
sed -i 's/Text("Package Filter: Blocklist", style = mobileHeadline)/Text(stringResource(R.string.package_filter_block), style = mobileHeadline)/g' "$FILE"
sed -i 's/Text("All packages except listed IDs are forwarded.", style = mobileCallout)/Text(stringResource(R.string.all_except_listed), style = mobileCallout)/g' "$FILE"
sed -i 's/Text("Search apps", style = mobileCaption1, color = mobileTextSecondary)/Text(stringResource(R.string.search_apps), style = mobileCaption1, color = mobileTextSecondary)/g' "$FILE"
sed -i 's/Text("Show System Apps", style = mobileHeadline)/Text(stringResource(R.string.show_system_apps), style = mobileHeadline)/g' "$FILE"
sed -i 's/Text("Include Android\/system packages in results.", style = mobileCallout)/Text(stringResource(R.string.include_system_packages), style = mobileCallout)/g' "$FILE"
sed -i 's/Text("Quiet Hours", style = mobileHeadline)/Text(stringResource(R.string.quiet_hours), style = mobileHeadline)/g' "$FILE"
sed -i 's/Text("Suppress forwarding during a local time window.", style = mobileCallout)/Text(stringResource(R.string.suppress_forwarding), style = mobileCallout)/g' "$FILE"
sed -i 's/Text("Quiet Start (HH:mm)", style = mobileCaption1, color = mobileTextSecondary)/Text(stringResource(R.string.quiet_start), style = mobileCaption1, color = mobileTextSecondary)/g' "$FILE"
sed -i 's/Text("Use 24-hour HH:mm format, for example 22:00.", style = mobileCaption1, color = mobileDanger)/Text(stringResource(R.string.quiet_start_hint), style = mobileCaption1, color = mobileDanger)/g' "$FILE"
sed -i 's/Text("Quiet End (HH:mm)", style = mobileCaption1, color = mobileTextSecondary)/Text(stringResource(R.string.quiet_end), style = mobileCaption1, color = mobileTextSecondary)/g' "$FILE"
sed -i 's/Text("Use 24-hour HH:mm format, for example 07:00.", style = mobileCaption1, color = mobileDanger)/Text(stringResource(R.string.quiet_end_hint), style = mobileCaption1, color = mobileDanger)/g' "$FILE"
sed -i 's/Text("Save Quiet Hours", style = mobileCallout.copy(fontWeight = FontWeight.Bold))/Text(stringResource(R.string.save_quiet_hours), style = mobileCallout.copy(fontWeight = FontWeight.Bold))/g' "$FILE"
sed -i 's/Text("Max Events \/ Minute", style = mobileCaption1, color = mobileTextSecondary)/Text(stringResource(R.string.max_events_minute), style = mobileCaption1, color = mobileTextSecondary)/g' "$FILE"
sed -i 's/Text("Save Rate", style = mobileCallout.copy(fontWeight = FontWeight.Bold))/Text(stringResource(R.string.save_rate), style = mobileCallout.copy(fontWeight = FontWeight.Bold))/g' "$FILE"
sed -i 's/Text("Blank keeps notification events on this device'\''s default notification route. Set a key only to pin forwarding into a different session.", style = mobileCaption1, color = mobileTextSecondary)/Text(stringResource(R.string.session_route_desc), style = mobileCaption1, color = mobileTextSecondary)/g' "$FILE"
sed -i 's/Text("Save Session Route", style = mobileCallout.copy(fontWeight = FontWeight.Bold))/Text(stringResource(R.string.save_session_route), style = mobileCallout.copy(fontWeight = FontWeight.Bold))/g' "$FILE"
sed -i 's/Text("Photos", style = mobileHeadline)/Text(stringResource(R.string.photos), style = mobileHeadline)/g' "$FILE"
sed -i 's/Text("Access recent photos.", style = mobileCallout)/Text(stringResource(R.string.access_recent_photos), style = mobileCallout)/g' "$FILE"
sed -i 's/Text("Contacts", style = mobileHeadline)/Text(stringResource(R.string.contacts), style = mobileHeadline)/g' "$FILE"
sed -i 's/Text("Search and add contacts.", style = mobileCallout)/Text(stringResource(R.string.search_add_contacts), style = mobileCallout)/g' "$FILE"
sed -i 's/Text("Calendar", style = mobileHeadline)/Text(stringResource(R.string.calendar), style = mobileHeadline)/g' "$FILE"
sed -i 's/Text("Read and create events.", style = mobileCallout)/Text(stringResource(R.string.read_create_events), style = mobileCallout)/g' "$FILE"
sed -i 's/Text("Call Log", style = mobileHeadline)/Text(stringResource(R.string.call_log), style = mobileHeadline)/g' "$FILE"
sed -i 's/Text("Search recent call history.", style = mobileCallout)/Text(stringResource(R.string.search_call_history), style = mobileCallout)/g' "$FILE"
sed -i 's/Text("Motion", style = mobileHeadline)/Text(stringResource(R.string.motion), style = mobileHeadline)/g' "$FILE"
sed -i 's/Text("Track steps and activity.", style = mobileCallout)/Text(stringResource(R.string.track_steps), style = mobileCallout)/g' "$FILE"

echo "✓ SettingsSheet.kt 汉化完成！"
