#!/bin/bash
FILE="apps/android/app/src/main/java/ai/openclaw/app/ui/ConnectTabScreen.kt"

# 替换各个字符串
sed -i 's/Text("Trust this gateway?", style = mobileHeadline, color = mobileText)/Text(stringResource(R.string.trust_gateway_title), style = mobileHeadline, color = mobileText)/g' "$FILE"
sed -i 's/Text("Trust and continue")/Text(stringResource(R.string.trust_and_continue))/g' "$FILE"
sed -i 's/Text("Cancel")/Text(stringResource(R.string.cancel))/g' "$FILE"
sed -i 's/Text("Gateway Connection", style = mobileTitle1, color = mobileText)/Text(stringResource(R.string.gateway_connection), style = mobileTitle1, color = mobileText)/g' "$FILE"
sed -i "s/Text(\"Endpoint\", style = mobileCaption1.copy(fontWeight = FontWeight.SemiBold), color = mobileTextSecondary)/Text(stringResource(R.string.endpoint), style = mobileCaption1.copy(fontWeight = FontWeight.SemiBold), color = mobileTextSecondary)/g" "$FILE"
sed -i "s/Text(\"Status\", style = mobileCaption1.copy(fontWeight = FontWeight.SemiBold), color = mobileTextSecondary)/Text(stringResource(R.string.status), style = mobileCaption1.copy(fontWeight = FontWeight.SemiBold), color = mobileTextSecondary)/g" "$FILE"
sed -i 's/Text("Disconnect", style = mobileHeadline.copy(fontWeight = FontWeight.SemiBold))/Text(stringResource(R.string.disconnect), style = mobileHeadline.copy(fontWeight = FontWeight.SemiBold))/g' "$FILE"
sed -i 's/Text("Connect Gateway", style = mobileHeadline.copy(fontWeight = FontWeight.Bold))/Text(stringResource(R.string.connect_gateway), style = mobileHeadline.copy(fontWeight = FontWeight.Bold))/g' "$FILE"
sed -i 's/Text("Copy Report for Claw", style = mobileCallout.copy(fontWeight = FontWeight.Bold))/Text(stringResource(R.string.copy_report), style = mobileCallout.copy(fontWeight = FontWeight.Bold))/g' "$FILE"
sed -i 's/Text("Advanced controls", style = mobileHeadline, color = mobileText)/Text(stringResource(R.string.advanced_controls), style = mobileHeadline, color = mobileText)/g' "$FILE"
sed -i 's/Text("Setup code, endpoint, TLS, token, password, onboarding.", style = mobileCaption1, color = mobileTextSecondary)/Text(stringResource(R.string.setup_controls_desc), style = mobileCaption1, color = mobileTextSecondary)/g' "$FILE"
sed -i "s/Text(\"Connection method\", style = mobileCaption1.copy(fontWeight = FontWeight.SemiBold), color = mobileTextSecondary)/Text(stringResource(R.string.connection_method), style = mobileCaption1.copy(fontWeight = FontWeight.SemiBold), color = mobileTextSecondary)/g" "$FILE"
sed -i 's/Text("Run these on the gateway host:", style = mobileCallout, color = mobileTextSecondary)/Text(stringResource(R.string.run_these), style = mobileCallout, color = mobileTextSecondary)/g' "$FILE"
sed -i "s/Text(\"Setup Code\", style = mobileCaption1.copy(fontWeight = FontWeight.SemiBold), color = mobileTextSecondary)/Text(stringResource(R.string.setup_code_label), style = mobileCaption1.copy(fontWeight = FontWeight.SemiBold), color = mobileTextSecondary)/g" "$FILE"
sed -i 's/placeholder = { Text("Paste setup code", style = mobileBody, color = mobileTextTertiary) }/placeholder = { Text(stringResource(R.string.paste_setup_code), style = mobileBody, color = mobileTextTertiary) }/g' "$FILE"
sed -i "s/Text(\"Host\", style = mobileCaption1.copy(fontWeight = FontWeight.SemiBold), color = mobileTextSecondary)/Text(stringResource(R.string.host_label), style = mobileCaption1.copy(fontWeight = FontWeight.SemiBold), color = mobileTextSecondary)/g" "$FILE"
sed -i 's/placeholder = { Text("10.0.2.2", style = mobileBody, color = mobileTextTertiary) }/placeholder = { Text(stringResource(R.string.default_host), style = mobileBody, color = mobileTextTertiary) }/g' "$FILE"
sed -i 's/Text("Use TLS", style = mobileHeadline, color = mobileText)/Text(stringResource(R.string.use_tls), style = mobileHeadline, color = mobileText)/g' "$FILE"
sed -i "s/Text(\"Token (optional)\", style = mobileCaption1.copy(fontWeight = FontWeight.SemiBold), color = mobileTextSecondary)/Text(stringResource(R.string.token_label), style = mobileCaption1.copy(fontWeight = FontWeight.SemiBold), color = mobileTextSecondary)/g" "$FILE"
sed -i 's/placeholder = { Text("token", style = mobileBody, color = mobileTextTertiary) }/placeholder = { Text(stringResource(R.string.token_hint), style = mobileBody, color = mobileTextTertiary) }/g' "$FILE"
sed -i "s/Text(\"Password (optional)\", style = mobileCaption1.copy(fontWeight = FontWeight.SemiBold), color = mobileTextSecondary)/Text(stringResource(R.string.password_label), style = mobileCaption1.copy(fontWeight = FontWeight.SemiBold), color = mobileTextSecondary)/g" "$FILE"
sed -i 's/placeholder = { Text("password", style = mobileBody, color = mobileTextTertiary) }/placeholder = { Text(stringResource(R.string.password_hint), style = mobileBody, color = mobileTextTertiary) }/g' "$FILE"
sed -i 's/Text("Run onboarding again", style = mobileCallout.copy(fontWeight = FontWeight.SemiBold), color = mobileAccent)/Text(stringResource(R.string.run_onboarding_again), style = mobileCallout.copy(fontWeight = FontWeight.SemiBold), color = mobileAccent)/g' "$FILE"
sed -i "s/Text(\"Resolved endpoint\", style = mobileCaption1.copy(fontWeight = FontWeight.SemiBold), color = mobileTextSecondary)/Text(stringResource(R.string.resolved_endpoint), style = mobileCaption1.copy(fontWeight = FontWeight.SemiBold), color = mobileTextSecondary)/g" "$FILE"

echo "✓ ConnectTabScreen.kt 汉化完成！"
